### ISSUE TITLE
Refactor: Code convention for control flows, and conditional statements

### ISSUE THREAD

**Issue by SanchieGuzman** [leonhard-leung/CS311-Final-Project#3]
# Description
Based on the current source code, the control flows, and conditional statements does not conform to the coding standards that our team have. Please make sure to follow our coding standards for control flows, and conditional statements in the following files:  

1. format.rs
2. debugging.rs
3. refactor.rs
4. lib.rs

## Example
Old convention
```
if b != 0 {
        let div = x / b;
        println!("Division: {}", div);
}
``` 
New convention
```
if b != 0 
    {
        let div = x / b;
        println!("Division: {}", div);
    }
```

## Team's Coding Standard
Please refer to the link below for our coding standard
https://docs.google.com/document/d/1UmMADx0csIDU4VLxZMvrCdyU-8UTqVLhLT-pddNE7iA/edit?tab=t.0

> If something's not clear, feel free to comment here

**Comment by Marius-Glenn-Nonato** [comment]
Hello,
I am going to take a look at them now.
