### ISSUE TITLE
Code Clean Up

### ISSUE THREAD

**Issue by JerwinKyleRamos** [leonhard-leung/CS311-Final-Project#6]
Hello,

Could you kindly modify the code for our project? I have noticed that some lines of code are not really necessary, like long comments on all files. Additionally, some lines of code are too long and do not comply with our coding standards.

Please make the necessary adjustments.

**Comment by Stephen-Coloma** [comment]
Sorry for this late reply, 

Sure. Once our teammates finished refactoring the code base, I will proceed immediately with the code clean up.

I will let you know when I'm finished.
